"""Add admin user

Revision ID: 17bead004563
Revises: f3ef8d65f19c
Create Date: 2025-08-11 03:25:01.341610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from passlib.context import CryptContext


# revision identifiers, used by Alembic.
revision: str = '17bead004563'
down_revision: Union[str, Sequence[str], None] = 'f3ef8d65f19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    # Seed admin user
    conn = op.get_bind()
    hashed = pwd_context.hash("password")
    conn.execute(sa.text("INSERT INTO users (username, email, password_hash, role) VALUES (:u, :e, :p, :r)"),
                 {"u": "admin", "e": "admin@admin.com", "p": hashed, "r": "admin"})


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
