"""Company Description

Revision ID: bf7cb0b0631b
Revises: 85a9a6d90649
Create Date: 2025-08-13 10:52:11.943313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf7cb0b0631b'
down_revision: Union[str, Sequence[str], None] = '85a9a6d90649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'description')
    # ### end Alembic commands ###
