"""Relationships

Revision ID: f3ef8d65f19c
Revises: 16af6d27d7ea
Create Date: 2025-08-11 02:59:49.946504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3ef8d65f19c'
down_revision: Union[str, Sequence[str], None] = '16af6d27d7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('max_tokens', sa.Integer(), nullable=False))
    op.add_column('pdf_files', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('pdf_files', 'file_size')
    op.drop_column('companies', 'max_tokens')
    # ### end Alembic commands ###
